/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
// export class Canvas {
//     constructor(width: number, height: number)
//     save(): void
//     translate(dx: number, dy: number): void
//     scale(sx: number, sy: number): void
//     moveTo(x: number, y: number): void
//     lineTo(x: number, y: number): void
//     quadTo(cpx: number, cpy: number, x: number, y: number): void
//     bezierCurveTo(cp1X: number, cp1Y: number, cp2X: number, cp2Y: number, x: number, y: number): void
//     closePath(): void
//     beginPath(): void
//     stroke(): void
//     fill(): void
//     setLineWidth(width: number): void
//     saveTo(file: string): void
//   }